#!/usr/bin/env python3
"""Crawl thaana.com → regenerate foundries/thaana/catalog.yaml.

A SOURCING tool, deliberately separate from build_manifest.py: it touches the network and thaana's HTML
(non-deterministic, can break if their page changes), so it only *writes the committed catalog* — which
a human then reviews in the diff before it ships. The build itself stays offline + reproducible.

thaana ships each family as per-format .zip archives on a detail page (thaana.com/<slug>/<Name>-<fmt>.zip),
all SIL OFL. We link to those (foundry-hosted → their download telemetry); `archive: zip` tells the app
to unpack + register. Variable families link `-vf.zip`, static families `-ttf.zip`.

Run it where there's network (locally / CI), then review `git diff foundries/thaana/catalog.yaml`:
  pip install requests beautifulsoup4 pyyaml
  python3 tools/crawl_thaana.py [--out foundries/thaana/catalog.yaml]

NOTE: it does NOT download the fonts — we link to thaana's zips. (A future flag could fetch each zip,
read the font name table for copyright/version, and switch the family to we-host on R2.)
"""
from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path
from urllib.parse import urljoin, urlparse, parse_qs

try:
    import requests
    from bs4 import BeautifulSoup
    import yaml
except ImportError:
    sys.exit("error: crawler needs `pip install requests beautifulsoup4 pyyaml`")

BASE = "https://thaana.com/"
UA = {"User-Agent": "tharikey-fonts-crawler (+https://tharikey.com)"}
DELAY = 1.0  # be polite — one request per second
HEADER = (
    "# Thaana.com families — GENERATED by tools/crawl_thaana.py. Review the diff before committing.\n"
    "# All free (SIL OFL, inherited from meta.yaml). Foundry-hosted: files[].url points at thaana.com's\n"
    "# own .zip; `archive: zip` tells the app to unpack + register. Switch a family to we-host by dropping\n"
    "# its binary in assets/ and removing url + archive.\n\n"
)


def get(url: str) -> BeautifulSoup:
    r = requests.get(url, headers=UA, timeout=30)
    r.raise_for_status()
    return BeautifulSoup(r.text, "html.parser")


EXCLUDE = {"", "about", "blog", "contact", "fonts", "license", "privacy", "terms", "index.html",
           "typist"}  # typist is an asset-generator tool, not a font


def discover_slugs(index: BeautifulSoup) -> list[str]:
    """Family detail pages are single-segment same-host paths (/bolhu/). Handles relative AND absolute
    hrefs (thaana's index uses absolute URLs); filters out nav/external links."""
    slugs, seen, sample = [], set(), []
    for a in index.select("a[href]"):
        p = urlparse(urljoin(BASE, a["href"]))
        if p.netloc.replace("www.", "") != urlparse(BASE).netloc:
            continue  # external link
        seg = p.path.strip("/")
        sample.append(seg)
        if re.fullmatch(r"[a-z0-9][a-z0-9-]*", seg) and seg not in EXCLUDE and seg not in seen:
            seen.add(seg)
            slugs.append(seg)
    if not slugs:
        uniq = sorted(set(sample))
        print(f"  debug: {len(sample)} same-host links, {len(uniq)} unique paths; "
              f"sample: {uniq[:30]}", file=sys.stderr)
    return slugs


def crawl_family(slug: str) -> dict | None:
    page = get(urljoin(BASE, f"{slug}/"))
    # Download hrefs end in .zip but carry a `?v=<version>` cache-bust query, e.g.
    # FanaraGolhi-vf.zip?v=2.10 — so match on the path, store the bare URL, capture the version.
    zips = []  # (path_lower, bare_url, version)
    for a in page.select("a[href]"):
        pr = urlparse(urljoin(BASE, a["href"]))
        if not pr.path.lower().endswith(".zip"):
            continue
        zips.append((pr.path.lower(), f"{pr.scheme}://{pr.netloc}{pr.path}",
                     parse_qs(pr.query).get("v", [None])[0]))
    vf = next((z for z in zips if "-vf.zip" in z[0]), None)
    ttf = next((z for z in zips if "-ttf.zip" in z[0]), None)
    chosen = vf or ttf  # desktop install wants ttf/vf, not woff/woff2
    if not chosen:
        print(f"  warn: {slug}: no ttf/vf .zip download found — skipped", file=sys.stderr)
        return None
    _, url, version = chosen
    variable = vf is not None
    h1 = page.find(["h1", "h2"])
    name = h1.get_text(strip=True) if h1 else slug.replace("-", " ").title()
    desc = next((t for p in page.find_all("p") if len(t := p.get_text(strip=True)) > 40), "")

    fam = {
        "id": slug,
        "name": name,
        "variable": variable,
        "files": [{"label": "Variable" if variable else "Static",
                   "format": "TTF", "archive": "zip", "url": url}],
    }
    if version:
        fam["version"] = version
    if desc:
        fam["description"] = desc
    return fam


def main() -> None:
    ap = argparse.ArgumentParser(description="Crawl thaana.com into the foundry catalog.")
    ap.add_argument("--out", default=str(Path(__file__).resolve().parent.parent
                                        / "foundries" / "thaana" / "catalog.yaml"))
    args = ap.parse_args()

    print(f"fetching {BASE} …")
    slugs = discover_slugs(get(BASE))
    print(f"discovered {len(slugs)} candidate family pages")

    families = []
    for slug in slugs:
        try:
            fam = crawl_family(slug)
        except requests.HTTPError:
            continue  # not a font page
        if fam:
            families.append(fam)
            print(f"  + {fam['id']} ({'variable' if fam['variable'] else 'static'})")
        time.sleep(DELAY)

    if not families:
        sys.exit("error: crawl found 0 families — NOT writing (existing catalog.yaml preserved). "
                 "See the debug line above for the link paths discovered.")

    Path(args.out).write_text(
        HEADER + yaml.safe_dump({"families": families}, allow_unicode=True, sort_keys=False, width=120),
        encoding="utf-8",
    )
    print(f"wrote {args.out} — {len(families)} families. Review the diff, then run build_manifest.py.")


if __name__ == "__main__":
    main()
